export const COMMONS_CONST = {
  CREATE_DATE: "Ngày tạo",
  STOCK: "Tồn kho",
  PRICE: "Giá tiền",
  SALE: "Giảm giá",
  COST: "Giá gốc",
  INFORMATION: "Thông tin",
  LOADING: "Vui lòng đợi !",
  PREVIOUS: "Trước",
  NEXT: "Sau",
  PAGE: "Trang",
  NAME: "Tên",
  DATA: "Dữ liệu",
  SAVE: "Lưu",
  DELETE: "Xoá",
  CANCEL: "Huỷ",
  STATUS: "Trạng thái",
  ALREADY_NAME: "Tên đã tồn tại",
  ERROR: "Lỗi không xác định",
  CREATE: "Tạo",
  BACK: "Quay lại",
  EDIT: "Chỉnh sửa",
  INVALID_EMAIL: "Email không đúng định dạng",
  UPPERCASE_PASSWORD: "Mật khẩu phải có kí tự in hoa",
  LOWERCASE_PASSWORD: "Mật khẩu phải có kí tự thường",
  NUMBER_PASSWORD: "Mật khẩu phải có kí tự số",
  SPECIAL_PASSWORD: "Mật khẩu phải có kí tự đặc biệt",
  ENTER_EMAIL: "Điền email vào đây",
  ENTER_NAME: "Điền tên vào đây",
  ENTER_PASSWORD: "Điền mật khẩu vào đây",
  MAIN_IMAGE: "Ảnh chính",
  EXTRA_IMAGES: "Ảnh phụ",
};
